Repository Recidiviz/covid19-dashboard, pull requests merged in 2020-05, with the labels that each got.

#301 [nit] Add vertical padding for the loading indicator when loading
  src/page-multi-facility/MultiFacilityPage.tsx
Labels: Subject: UI, Type: Enhancement

#316 [R(t)] UX - Add R(t) number to Scenario View
  src/constants/EpidemicModel.tsx
  src/design-system/ChartWrapper.tsx
  src/design-system/Colors.tsx
  src/design-system/FontSizes.tsx
  src/design-system/PillCircle.tsx
  src/page-multi-facility/FacilityRow.tsx
  src/page-multi-facility/FacilityRowRtValuePill.tsx
  src/rt-timeseries/RtTimeseries.tsx
Labels: Subject: UI, Type: Feature

#324 Fix issue preventing scenario changes from updating database
  src/page-multi-facility/ScenarioSidebar.tsx
Labels: Type: Bug

#446 Get facilities RtData by facility ID on response impact page
  src/hooks/useFacilitiesRtData.tsx
  src/page-response-impact/ResponseImpactDashboard.tsx
Labels: Type: Bug

#483 Remove unused pages
  src/news-feed-events/NewsFeed.tsx
  src/news-feed-events/NewsFeedEvent.tsx
  src/page-form/FormPage.tsx
  src/page-form/components/Form.tsx
  src/page-home/HomePage.tsx
  src/page-test/TestPage.tsx
Labels: Type: Tech Debt
