Repository Recidiviz/covid19-dashboard, pull requests merged in 2020-04, with the labels that each got.

#104 Add Modal components for MultiFacilityPage
  index.html
  src/@types/svg.d.ts
  src/design-system/Colors.tsx
  src/design-system/InputButton.tsx
  src/design-system/Modal.tsx
  src/design-system/ModalDialog.tsx
  src/design-system/ModalSteps.tsx
  src/design-system/ModalTitle.tsx
  src/design-system/icons/ic_close.svg
  src/page-multi-facility/AddFacilityModal.tsx
  src/page-multi-facility/MultiFacilityPage.tsx
Labels: Type: Feature

#134 Jen/unnamed facility
  src/design-system/InputCheckbox.tsx
  src/entry-point-client/PageList.tsx
  src/impact-dashboard/FormGrid.tsx
  src/impact-dashboard/MitigationInformation.tsx
  src/page-unnamed-facility/FacilityInformationSection.tsx
  src/page-unnamed-facility/LocaleInformationSection.tsx
  src/page-unnamed-facility/RateOfSpreadSection.tsx
  src/page-unnamed-facility/UnnamedFacilityPage.tsx
Labels: WIP

#210 Remove unused AddFacilityModal
  src/page-multi-facility/AddFacilityModal.tsx
Labels: Type: Tech Debt

#212 Add tick values in increments of 25 to facility output chart
  src/impact-dashboard/CurveChart.tsx
Labels: Subject: UI

#211 Set welcome font size to 16px
  src/design-system/Colors.tsx
  src/page-multi-facility/CreateBaselineScenarioPage.tsx
Labels: Subject: UI
